# Generated by Django 5.2.4 on 2025-08-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasepilates',
            options={'ordering': ['-fecha', 'horario']},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-fecha_envio']},
        ),
        migrations.AlterModelOptions(
            name='reservaclase',
            options={'ordering': ['-fecha_reserva']},
        ),
        migrations.AlterField(
            model_name='reservaclase',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_clase', related_query_name='reserva_clase', to=settings.AUTH_USER_MODEL),
        ),
    ]
