# Generated by Django 5.2.4 on 2025-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_clasepilates_options_alter_contacto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('instructor', models.CharField(blank=True, help_text='Opcional', max_length=100)),
                ('capacidad', models.PositiveSmallIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloque horario',
                'verbose_name_plural': 'Bloques horarios',
                'ordering': ('dia_semana', 'hora_inicio'),
            },
        ),
    ]
