# Generated by Django 5.2.4 on 2025-08-27 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0002_alter_clasepilates_options_alter_contacto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Reformer', 'Reformer'), ('Mat', 'Mat'), ('Grupal', 'Grupal')], max_length=20)),
                ('fecha', models.DateField()),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='Confirmada', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.clasepilates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'tipo', 'fecha', 'inicio'), name='uniq_reserva_usuario_tipo_fecha_hora')],
            },
        ),
    ]
