# Generated by Django 5.2.4 on 2025-08-13 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reformer', 'Reformer'), ('mat', 'Mat'), ('grupal', 'Grupal')], max_length=20)),
                ('fecha', models.DateField()),
                ('inicio', models.TimeField()),
                ('fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada')], default='Confirmada', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_index', related_query_name='reserva_index', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-inicio'],
            },
        ),
    ]
