# Generated by Django 5.2.4 on 2025-08-27 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_clasepilates_options_alter_contacto_options_and_more'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='administrador.clasepilates'),
        ),
    ]
