# Generated by Django 5.2.4 on 2025-08-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_reserva_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='clase',
        ),
    ]
