# Generated by Django 5.2.4 on 2025-08-28 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_alter_clasepilates_options_alter_contacto_options_and_more'),
        ('index', '0003_remove_reserva_clase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_index', to='administrador.clasepilates'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('user', 'clase'), name='uniq_reserva_usuario_misma_clase'),
        ),
    ]
