# Generated by Django 5.2.4 on 2025-08-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='comentario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='estado_mensaje',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('respondido', 'Respondido')], default='pendiente', max_length=12),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
