# Generated by Django 3.1.12 on 2025-09-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_contacto_comentario_contacto_estado_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
